---

stages:
  - release

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
  script: |
    # GITLAB_TOKEN is needed to create GitLab releases.
    # CI_JOB_TOKEN is needed if use_job_token is set.
    # DOCKER_* are needed to push Docker images.
    docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} registry.gitlab.com
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/zobtube/zobtube \
      -w /go/src/gitlab.com/zobtube/zobtube \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME \
      -e DOCKER_PASSWORD \
      -e DOCKER_REGISTRY \
      -e GITLAB_TOKEN \
      goreleaser/goreleaser release --clean
