---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - formats: [binary]
    name_template: >-
      {{ .ProjectName }}_v
      {{- .Major }}.{{ .Minor }}.{{ .Patch }}_
      {{- tolower .Os }}_
      {{- tolower .Arch }}
    format_overrides:
      - goos: windows
        formats: zip

dockers:
  - image_templates:
      - "ghcr.io/zobtube/zobtube:{{ .Version }}"
      - "ghcr.io/zobtube/zobtube:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/zobtube/zobtube"
    use: buildx
