// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag/v2"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{}
