---

name: go-test
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test with Go CLI
        run: go test ./...
