---

name: go-test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test with Go CLI
        run: go test ./... 
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: false
          amend: true
        if: |
          github.event_name == 'push'
        continue-on-error: true
